apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
spec:
  schedule: "40 * * * *"
  startingDeadlineSeconds: 300
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 360
      template:
        spec:
          containers:
          - name: django-clear-sessions
            image: docker.io/library/test-django-app:latest
            imagePullPolicy: IfNotPresent
            command:
            - python
            - manage.py
            - clearsessions
            env:
            envFrom:
              - secretRef:
                  name: test-django-app-secret
          restartPolicy: Never
