---
apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
spec:
  template:
    spec:
      containers:
        - name: django-migrate
          image: docker.io/library/test-django-app:latest
          imagePullPolicy: IfNotPresent
          command: ["python", "manage.py", "migrate"]
          envFrom:
            - secretRef:
                name: test-django-app-secret
      restartPolicy: Never